<p>Archie is 11yr old and loves solving maths puzzles there is this clique in Archie's school who are taking in new members and Archie really wants to become part of it as these guys get to do a lot of cool stuff, but they want only smart kids in their gang so they came up with this riddle only those who are able to solve this can join them.</p>
<p>James is inside club room If charlie Knocks the door James will say a random number X: 1&lt;=X&lt;10000 and then Charlie would tell him the secret-code; actually this riddle is nothing but what they use to ensure person knocking the door is their club member, so if someone is able to decipher this code, is worthy of becoming their gang member and they obviously would like him/her to be on their side .)</p>
<p><br />If James says: 4435<br />Charlie would say: 484764<br />If James says: 298<br />Charlie would say: 3765<br />If James says: 200<br />Charlie would say: 37<br />If James says: 1001<br />Charlie would say: 383</p>
<p><span style="color: #999999;">[XXXXXXXXX <em>SPOILER 1 </em>XXXXXXXXXXX]</span><br /><span style="color: #999999;">Archie was able to figure out this much </span><br /><span style="color: #999999;">If James says: 4127</span><br /><span style="color: #999999;">then Charlie must be writing the number in words</span><br /><span style="color: #999999;">ie 4127 as four thousand one hundred twenty seven </span><br /><span style="color: #999999;">[XXXXXXXXXXXXXXXXXXXXXXXXXXXX]</span><br /><br /><strong>Can you help Archie decipher rest of this riddle?&nbsp;</strong></p>
<p>Input: 10 lines each containing a single number X: 1 &lt;=X &lt; 10000<br />Output: print encrypted number<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;print translation of that number into words<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;print secret-code: decrypted the number<br /><br /><strong>Sample Input:</strong><br />3324<br />158<br />2314<br />8849<br />8643<br />2252<br />7155<br />6155<br />3057<br />1572</p>
<p><br />[OUTPUT IS CASE SENSITIVE]<br /><strong>Sample Output:</strong></p>
<p>3324<br />three thousand three hundred twenty four<br />secret-code 585764<br />158<br />one hundred fifty eight<br />secret-code 3755<br />2314<br />two thousand three hundred fourteen<br />secret-code 38578<br />8849<br />eight thousand eight hundred forty nine<br />secret-code 585754<br />8643<br />eight thousand six hundred forty three<br />secret-code 583755<br />2252<br />two thousand two hundred fifty two<br />secret-code 383753<br />7155<br />seven thousand one hundred fifty five<br />secret-code 583754<br />6155<br />six thousand one hundred fifty five<br />secret-code 383754<br />3057<br />three thousand fifty seven<br />secret-code 5855<br />1572<br />one thousand five hundred seventy two<br />secret-code 384773<span style="color: #999999;"><br /></span>three thousand fifty seven<br />secret-code 5855<br />1572<br />one thousand five hundred seventy two<br />secret-code 384773</p>
<p>&nbsp;</p>
<p><span style="color: #999999;">[XXXXXXXXX <em>SPOILER</em> 2 XXXXXXXXXXX]</span><br /><span style="color: #999999;">After spelling out each digit in number count the number of letters in each word then append them</span><br /><span style="color: #999999;">eg if number is 4127 spell it and then count it out like this four(4) thousand(8) one(3) hundred(7) twenty(6) seven(5)&nbsp; which gives 483765</span><br /><span style="color: #999999;">[XXXXXXXXXXXXXXXXXXXXXXXXXXXXX]</span><strong>&nbsp; &nbsp;&nbsp;&nbsp;</strong>&nbsp;</p>
